### ISSUE TITLE
Config missing ?

### ISSUE THREAD

**Issue by vinaypatel** [signalapp/storage-service#2]
Sample config is missing and the build generates error without config.

gitignore seems worked well here ! :)

**Comment by vinaypatel** [comment]
Anyone can help here ?

**Comment by bpajer** [comment]
I am having the same problem... does anyone have this config file?
I cannot build the storage service without it...

Please help

**Comment by ashwanisahotta1987** [comment]
Even I am looking for the Same Config File . I have also faced the same issue while starting up the Storage service. Ned the config Sample , Please help
